=== IkumiMine/Support-Ticket-System/xml/tickets-support-ticket.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tickets">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ticket" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="number" type="xs:positiveInteger" />
              <xs:element name="dateOfIssue" type="xs:dateTime" />
              <xs:element name="status" type="typeOfStatus" />
              <xs:element name="userId" type="xs:positiveInteger" />
              <xs:element name="inquiryType" type="typeOfInqury" />
              <xs:element name="messages">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="message" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="userId" type="xs:positiveInteger" />
                            <xs:attribute name="userName" type="xs:string" />
                            <xs:attribute name="sendDateTime" type="xs:dateTime" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
   
  <!--custom data type-->
  <xs:simpleType name="typeOfStatus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="New" />
      <xs:enumeration value="On-going" />
      <xs:enumeration value="Resolved" />
    </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="typeOfInqury">
    <xs:restriction base="xs:string">
      <xs:enumeration value="General" />
      <xs:enumeration value="Products" />
      <xs:enumeration value="Exchange and return" />
      <xs:enumeration value="Careers" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== IkumiMine/Support-Ticket-System/xml/tickets-support-ticket.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tickets-support-ticket.xsd">
    <ticket>
        <number>1</number>
        <dateOfIssue>2021-01-31T17:24:49</dateOfIssue>
        <status>On-going</status>
        <userId>0001</userId>
        <inquiryType>Products</inquiryType>
        <messages>
            <message userId="0001" userName="Ikumi Mine" sendDateTime="2021-01-31T12:30:06">I am interested in purchasing a sweater whose product number is ac0921. I am wondering if you have xs-size for it? I couldn't find information for it on your website.</message>
        <message userId="0001" userName="Ikumi Mine" sendDateTime="2021-04-03T12:48:38-04:00">test</message>
        </messages>
    </ticket>
    <ticket>
        <number>2</number>
        <dateOfIssue>2021-02-27T17:24:49</dateOfIssue>
        <status>New</status>
        <userId>0001</userId>
        <inquiryType>General</inquiryType>
        <messages>
            <message userId="0001" userName="Ikumi Mine" sendDateTime="2021-02-28T12:30:06">I am interested in purchasing a sweater whose product number is ac0921. I am wondering if you have xs-size for it? I couldn't find information for it on your website.</message>
        <message userId="0002" userName="Rey Abdul" sendDateTime="2021-04-02T22:54:26-04:00">answer</message></messages>
    </ticket>
<ticket><number>3</number><dateOfIssue>2021-04-02T22:04:45-04:00</dateOfIssue><status>On-going</status><userId>0001</userId><inquiryType>Products</inquiryType><messages><message userId="0001" userName="Ikumi Mine" sendDateTime="2021-04-02T22:04:45-04:00">test</message><message userId="0002" userName="Rey Abdul" sendDateTime="2021-04-03T12:39:35-04:00">test</message></messages></ticket><ticket><number>4</number><dateOfIssue>2021-05-18T14:20:26-04:00</dateOfIssue><status>On-going</status><userId>0001</userId><inquiryType>Careers</inquiryType><messages><message userId="0001" userName="Ikumi Mine" sendDateTime="2021-05-18T14:20:26-04:00">test</message><message userId="0002" userName="Rey Abdul" sendDateTime="2021-05-18T14:36:28-04:00">test</message></messages></ticket></tickets>
