=== IkumiMine/Support-Ticket-System/xml/users-support-ticket.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="userId">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:positiveInteger">
                      <xs:attribute name="userType" type="xs:string" use="required" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="password" type="xs:string" />
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string" />
                    <xs:element name="middle" type="xs:string" minOccurs="0" />
                    <xs:element name="last" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="email" type="xs:string" />
              <xs:element name="phoneNumber" type="xs:positiveInteger" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== IkumiMine/Support-Ticket-System/xml/users-support-ticket.xml
<?xml version="1.0" encoding="utf-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users-support-ticket.xsd">
  <user>
    <userId userType="client">0001</userId>
    <password>71112dcbe9a8ff9c204efb09d30a1f40</password>
    <name>
      <first>Ikumi</first>
      <last>Mine</last>
    </name>
    <email>ikumine@gmail.com</email>
    <phoneNumber>4169961900</phoneNumber>
  </user>
  <user>
    <userId userType="staff">0002</userId>
    <password>80c2868bbcc6f7432d5598670fc853ed</password>
    <name>
      <first>Rey</first>
      <last>Abdul</last>
    </name>
    <email>reyabdul@gmail.com</email>
    <phoneNumber>6477396303</phoneNumber>
  </user>
</users>
